import {
  Users,
  Briefcase,
  CalendarCheck,
  GraduationCap,
  TrendingUp,
  Award,
  Banknote,
  UserCheck,
  Zap,
  PlusSquare,
  BarChart3,
  MessageSquare,
  UserCog,
  FileText,
} from 'lucide-react';

const ICON_SIZE = 20;
const ICON_COLOR = '#035F5B';

export const AVAILABLE_WIDGETS = {
  workforce: {
    id: 'workforce',
    title: 'Workforce Overview',
    description: 'Overview of workforce metrics and statistics',
    icon: <Users size={ICON_SIZE} color={ICON_COLOR} />,
    defaultLayout: { w: 8, h: 3.65, minW: 7, maxW: 8, minH: 3.65, maxH: 3.65 },
    removable: true,
  },
  recruitment: {
    id: 'recruitment',
    title: 'Recruitment Metrics',
    description: 'Track recruitment progress and metrics',
    icon: <Briefcase size={ICON_SIZE} color={ICON_COLOR} />,
    defaultLayout: { w: 4, h: 3.65, minW: 3, maxW: 6, minH: 3.65, maxH: 3.65 },
    removable: true,
  },
  attendance: {
    id: 'attendance',
    title: 'Attendance & Leave',
    description: 'Monitor attendance and leave requests',
    icon: <CalendarCheck size={ICON_SIZE} color={ICON_COLOR} />,
    defaultLayout: { w: 4, h: 3, minW: 3, maxW: 5, minH: 3, maxH: 3 },
    removable: true,
  },
  training: {
    id: 'training',
    title: 'Training Progress',
    description: 'Track employee training progress',
    icon: <GraduationCap size={ICON_SIZE} color={ICON_COLOR} />,
    defaultLayout: { w: 4, h: 3, minW: 3, maxW: 5, minH: 3, maxH: 3 },
    removable: true,
  },
  turnover: {
    id: 'turnover',
    title: 'Turnover & Retention',
    description: 'Monitor turnover and retention metrics',
    icon: <TrendingUp size={ICON_SIZE} color={ICON_COLOR} />,
    defaultLayout: { w: 4, h: 3, minW: 3, maxW: 5, minH: 3, maxH: 3 },
    removable: true,
  },
  performance: {
    id: 'performance',
    title: 'Performance Summary',
    description: 'View performance metrics and summaries',
    icon: <Award size={ICON_SIZE} color={ICON_COLOR} />,
    defaultLayout: { w: 4, h: 2.4, minW: 3, maxW: 5, minH: 2.4, maxH: 2.4 },
    removable: true,
  },
  payroll: {
    id: 'payroll',
    title: 'Payroll Summary',
    description: 'Overview of payroll information',
    icon: <Banknote size={ICON_SIZE} color={ICON_COLOR} />,
    defaultLayout: { w: 4, h: 2, minW: 3, maxW: 4, minH: 2, maxH: 2 },
    removable: true,
  },
  myApprovals: {
    id: 'myApprovals',
    title: 'My Pending Approvals',
    description: 'Review and manage pending approvals',
    icon: <UserCheck size={ICON_SIZE} color={ICON_COLOR} />,
    defaultLayout: { w: 4, h: 3.1, minW: 3, maxW: 4, minH: 3.1, maxH: 3.1 },
    removable: true,
  },
  quickActions: {
    id: 'quickActions',
    title: 'Quick Actions',
    description: 'Quick access to common actions',
    icon: <Zap size={ICON_SIZE} color={ICON_COLOR} />,
    defaultLayout: { w: 4, h: 3, minW: 3, maxW: 5, minH: 3, maxH: 3 },
    removable: true,
  },
  quickCreate: {
    id: 'quickCreate',
    title: 'Quick Create',
    description: 'Create new items quickly',
    icon: <PlusSquare size={ICON_SIZE} color={ICON_COLOR} />,
    defaultLayout: { w: 4, h: 2.2, minW: 3, maxW: 4, minH: 2.2, maxH: 2.2 },
    removable: true,
  },
  whosOnLeave: {
    id: 'whosOnLeave',
    title: "Who's On Leave This Week",
    description: 'View employees on leave this week',
    icon: <Users size={ICON_SIZE} color={ICON_COLOR} />,
    defaultLayout: { w: 5, h: 3, minW: 5, maxW: 6, minH: 3, maxH: 3 },
    removable: true,
  },
  departmentHeadcount: {
    id: 'departmentHeadcount',
    title: 'Department Headcount',
    description: 'View department headcount distribution',
    icon: <BarChart3 size={ICON_SIZE} color={ICON_COLOR} />,
    defaultLayout: { w: 4, h: 1.6, minW: 3, maxW: 5, minH: 1.6, maxH: 1.6 },
    removable: true,
  },
  workforceDemographics: {
    id: 'workforceDemographics',
    title: 'Workforce Demographics',
    description: 'View workforce demographics by age groups and tenure',
    icon: <Users size={ICON_SIZE} color={ICON_COLOR} />,
    defaultLayout: { w: 6, h: 3.3, minW: 4, maxW: 6, minH: 3.3, maxH: 3.3 },
    removable: true,
  },
  leaveTrend: {
    id: 'leaveTrend',
    title: 'Leave Trend (30 Days)',
    description: 'View leave trends over the last 30 days',
    icon: <TrendingUp size={ICON_SIZE} color={ICON_COLOR} />,
    defaultLayout: { w: 6, h: 3, minW: 4, maxW: 6, minH: 3, maxH: 3 },
    removable: true,
  },
  openPositions: {
    id: 'openPositions',
    title: 'Open Positions',
    description: 'Track open job positions and average time to fill',
    icon: <Briefcase size={ICON_SIZE} color={ICON_COLOR} />,
    defaultLayout: { w: 6, h: 3, minW: 4, maxW: 6, minH: 3, maxH: 3 },
    removable: true,
  },
  upcomingInterviews: {
    id: 'upcomingInterviews',
    title: 'Upcoming Interviews',
    description: 'View upcoming interview schedule',
    icon: <CalendarCheck size={ICON_SIZE} color={ICON_COLOR} />,
    defaultLayout: { w: 6, h: 3, minW: 4, maxW: 6, minH: 3, maxH: 3 },
    removable: true,
  },
  payslipsDeliveredStatus: {
    id: 'payslipsDeliveredStatus',
    title: 'Payslips Delivered Status',
    description: 'Track payslip delivery status and statistics',
    icon: <Banknote size={ICON_SIZE} color={ICON_COLOR} />,
    defaultLayout: { w: 6, h: 2.3, minW: 4, maxW: 6, minH: 2.3, maxH: 2.3 },
    removable: true,
  },
  reviewsStatus: {
    id: 'reviewsStatus',
    title: 'Reviews Status',
    description: 'View performance reviews status overview',
    icon: <Award size={ICON_SIZE} color={ICON_COLOR} />,
    defaultLayout: { w: 4, h: 2.2, minW: 4, maxW: 4, minH: 2.2, maxH: 2.2 },
    removable: true,
  },
  payrollExceptions: {
    id: 'payrollExceptions',
    title: 'Payroll Exceptions',
    description: 'View payroll exceptions and issues',
    icon: <Banknote size={ICON_SIZE} color={ICON_COLOR} />,
    defaultLayout: { w: 4, h: 2.4, minW: 3, maxW: 5, minH: 2.4, maxH: 2.4 },
    removable: true,
  },
  hiringOverview: {
    id: 'hiringOverview',
    title: 'Hiring Overview',
    description: 'View recruitment funnel and hiring progress',
    icon: <Briefcase size={ICON_SIZE} color={ICON_COLOR} />,
    defaultLayout: { w: 4, h: 3.5, minW: 4, maxW: 4, minH: 3.5, maxH: 3.5 },
    removable: true,
  },
  diversityMix: {
    id: 'diversityMix',
    title: 'Diversity Mix',
    description: 'View gender and diversity breakdown',
    icon: <Users size={ICON_SIZE} color={ICON_COLOR} />,
    defaultLayout: { w: 4, h: 2, minW: 4, maxW: 4, minH: 2, maxH: 2 },
    removable: true,
  },
  leaveRequestsSnapshot: {
    id: 'leaveRequestsSnapshot',
    title: 'Leave Requests Snapshot',
    description: 'Quick view of leave request status',
    icon: <CalendarCheck size={ICON_SIZE} color={ICON_COLOR} />,
    defaultLayout: { w: 6, h: 2, minW: 5, maxW: 6, minH: 2, maxH: 2},
    removable: true,
  },
  headcountSummary: {
    id: 'headcountSummary',
    title: 'Headcount Summary',
    description: 'View key headcount metrics and statistics',
    icon: <Users size={ICON_SIZE} color={ICON_COLOR} />,
    defaultLayout: { w: 6, h: 1.4, minW: 4, maxW: 6, minH: 1.4, maxH: 1.4 },
    removable: true,
  },
  todaysAbsentees: {
    id: 'todaysAbsentees',
    title: "Today's Absentees",
    description: 'View employees absent today with leave type',
    icon: <Users size={ICON_SIZE} color={ICON_COLOR} />,
    defaultLayout: { w: 4, h: 1.8, minW: 4, maxW: 5, minH: 1.8, maxH: 1.8 },
    removable: true,
  },
  timeToHireTrend: {
    id: 'timeToHireTrend',
    title: 'Time to Hire Trend',
    description: 'Track time to hire trends over time',
    icon: <TrendingUp size={ICON_SIZE} color={ICON_COLOR} />,
    defaultLayout: { w: 5, h: 3, minW: 4, maxW: 5, minH: 3, maxH: 3 },
    removable: true,
  },
  feedbackPulse: {
    id: 'feedbackPulse',
    title: 'Feedback Pulse',
    description: 'Track employee feedback and sentiment trends',
    icon: <MessageSquare size={ICON_SIZE} color={ICON_COLOR} />,
    defaultLayout: { w: 4, h: 2.5, minW: 4, maxW: 5, minH: 2.5, maxH: 2.5 },
    removable: true,
  },
  activeEnrollments: {
    id: 'activeEnrollments',
    title: 'Active Enrollments',
    description: 'View active course enrollments and overdue items',
    icon: <GraduationCap size={ICON_SIZE} color={ICON_COLOR} />,
    defaultLayout: { w: 4, h: 3, minW: 4, maxW: 5, minH: 3, maxH: 3},
    removable: true,
  },
  completionRateTrend: {
    id: 'completionRateTrend',
    title: 'Completion Rate Trend',
    description: 'Track course completion rate trends over time',
    icon: <TrendingUp size={ICON_SIZE} color={ICON_COLOR} />,
    defaultLayout: { w: 4, h: 3, minW: 4, maxW: 5, minH: 3, maxH: 3 },
    removable: true,
  },
  recommendedCourses: {
    id: 'recommendedCourses',
    title: 'Recommended Courses',
    description: 'View recommended training courses',
    icon: <GraduationCap size={ICON_SIZE} color={ICON_COLOR} />,
    defaultLayout: { w: 5, h: 1.4, minW: 5, maxW: 5, minH: 1.4, maxH: 1.4 },
    removable: true,
  },
  certificationsExpiringSoon: {
    id: 'certificationsExpiringSoon',
    title: 'Certifications Expiring Soon',
    description: 'Track certifications nearing expiry',
    icon: <Award size={ICON_SIZE} color={ICON_COLOR} />,
    defaultLayout: { w: 4, h: 2.4, minW: 4, maxW: 4, minH: 2.4, maxH: 2.4 },
    removable: true,
  },
  documentExpiryAlerts: {
    id: 'documentExpiryAlerts',
    title: 'Document Expiry Alerts',
    description: 'Track document expiration dates and alerts',
    icon: <UserCog size={ICON_SIZE} color={ICON_COLOR} />,
    defaultLayout: { w: 4, h: 2.8, minW: 4, maxW: 4, minH: 2.8, maxH: 2.8 },
    removable: true,
  },
  auditActivity: {
    id: 'auditActivity',
    title: 'Audit Activity (Last 24h)',
    description: 'View recent audit activities and logs',
    icon: <UserCog size={ICON_SIZE} color={ICON_COLOR} />,
    defaultLayout: { w: 5, h: 2.3, minW: 5, maxW: 5, minH: 2.3, maxH: 2.3 },
    removable: true,
  },
  complianceChecklistProgress: {
    id: 'complianceChecklistProgress',
    title: 'Compliance Checklist Progress',
    description: 'Track compliance checklist completion progress',
    icon: <UserCog size={ICON_SIZE} color={ICON_COLOR} />,
    defaultLayout: { w: 5, h: 2.2, minW: 5, maxW: 5, minH: 2.2, maxH: 2.2 },
    removable: true,
  },
  integrationHealthStatus: {
    id: 'integrationHealthStatus',
    title: 'Integration Health Status',
    description: 'Monitor the health status of system integrations',
    icon: <UserCog size={ICON_SIZE} color={ICON_COLOR} />,
    defaultLayout: { w: 5, h: 2.2, minW: 4, maxW: 5, minH: 2.2, maxH: 2.2 },
    removable: true,
  },
  alertsEscalationsSummary: {
    id: 'alertsEscalationsSummary',
    title: 'Alerts & Escalations Summary',
    description: 'View escalation counts and unread critical alerts',
    icon: <UserCog size={ICON_SIZE} color={ICON_COLOR} />,
    defaultLayout: { w: 5, h: 1.5, minW: 5, maxW: 5, minH: 1.5, maxH: 1.5 },
    removable: true,
  },
  nextPayrollCountdown: {
    id: 'nextPayrollCountdown',
    title: 'Next Payroll Countdown',
    description: 'Countdown to the next payroll processing date',
    icon: <UserCog size={ICON_SIZE} color={ICON_COLOR} />,
    defaultLayout: { w: 4, h: 2, minW: 3, maxW: 4, minH: 2, maxH: 2 },
    removable: true,
  },
  goalCompletionSnapshot: {
    id: 'goalCompletionSnapshot',
    title: 'Goal Completion Snapshot',
    description: 'Overview of goal completion rate and schedule status',
    icon: <UserCog size={ICON_SIZE} color={ICON_COLOR} />,
    defaultLayout: { w: 4, h: 2, minW: 4, maxW: 4, minH: 2, maxH: 2 },
    removable: true,
  },
};


export const getAllWidgetIds = () => Object.keys(AVAILABLE_WIDGETS);

export const getWidgetMetadata = (widgetId) => AVAILABLE_WIDGETS[widgetId];

export const getAvailableWidgetsForAdding = (currentLayout) => {
  const currentWidgetIds = new Set(currentLayout.map(item => item.i));
  return getAllWidgetIds().filter(widgetId => !currentWidgetIds.has(widgetId));
};

export const getAvailableWidgetsInfo = (currentLayout) => {
  return getAvailableWidgetsForAdding(currentLayout).map(widgetId => ({
    ...AVAILABLE_WIDGETS[widgetId],
  }));
};
